// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package authmethodldap

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktf/provider-boundary.authMethodLdap.AuthMethodLdap",
		reflect.TypeOf((*AuthMethodLdap)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "accountAttributeMaps", GoGetter: "AccountAttributeMaps"},
			_jsii_.MemberProperty{JsiiProperty: "accountAttributeMapsInput", GoGetter: "AccountAttributeMapsInput"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "anonGroupSearch", GoGetter: "AnonGroupSearch"},
			_jsii_.MemberProperty{JsiiProperty: "anonGroupSearchInput", GoGetter: "AnonGroupSearchInput"},
			_jsii_.MemberProperty{JsiiProperty: "bindDn", GoGetter: "BindDn"},
			_jsii_.MemberProperty{JsiiProperty: "bindDnInput", GoGetter: "BindDnInput"},
			_jsii_.MemberProperty{JsiiProperty: "bindPassword", GoGetter: "BindPassword"},
			_jsii_.MemberProperty{JsiiProperty: "bindPasswordHmac", GoGetter: "BindPasswordHmac"},
			_jsii_.MemberProperty{JsiiProperty: "bindPasswordHmacInput", GoGetter: "BindPasswordHmacInput"},
			_jsii_.MemberProperty{JsiiProperty: "bindPasswordInput", GoGetter: "BindPasswordInput"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "certificates", GoGetter: "Certificates"},
			_jsii_.MemberProperty{JsiiProperty: "certificatesInput", GoGetter: "CertificatesInput"},
			_jsii_.MemberProperty{JsiiProperty: "clientCertificate", GoGetter: "ClientCertificate"},
			_jsii_.MemberProperty{JsiiProperty: "clientCertificateInput", GoGetter: "ClientCertificateInput"},
			_jsii_.MemberProperty{JsiiProperty: "clientCertificateKey", GoGetter: "ClientCertificateKey"},
			_jsii_.MemberProperty{JsiiProperty: "clientCertificateKeyHmac", GoGetter: "ClientCertificateKeyHmac"},
			_jsii_.MemberProperty{JsiiProperty: "clientCertificateKeyHmacInput", GoGetter: "ClientCertificateKeyHmacInput"},
			_jsii_.MemberProperty{JsiiProperty: "clientCertificateKeyInput", GoGetter: "ClientCertificateKeyInput"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "dereferenceAliases", GoGetter: "DereferenceAliases"},
			_jsii_.MemberProperty{JsiiProperty: "dereferenceAliasesInput", GoGetter: "DereferenceAliasesInput"},
			_jsii_.MemberProperty{JsiiProperty: "description", GoGetter: "Description"},
			_jsii_.MemberProperty{JsiiProperty: "descriptionInput", GoGetter: "DescriptionInput"},
			_jsii_.MemberProperty{JsiiProperty: "discoverDn", GoGetter: "DiscoverDn"},
			_jsii_.MemberProperty{JsiiProperty: "discoverDnInput", GoGetter: "DiscoverDnInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableGroups", GoGetter: "EnableGroups"},
			_jsii_.MemberProperty{JsiiProperty: "enableGroupsInput", GoGetter: "EnableGroupsInput"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "groupAttr", GoGetter: "GroupAttr"},
			_jsii_.MemberProperty{JsiiProperty: "groupAttrInput", GoGetter: "GroupAttrInput"},
			_jsii_.MemberProperty{JsiiProperty: "groupDn", GoGetter: "GroupDn"},
			_jsii_.MemberProperty{JsiiProperty: "groupDnInput", GoGetter: "GroupDnInput"},
			_jsii_.MemberProperty{JsiiProperty: "groupFilter", GoGetter: "GroupFilter"},
			_jsii_.MemberProperty{JsiiProperty: "groupFilterInput", GoGetter: "GroupFilterInput"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "insecureTls", GoGetter: "InsecureTls"},
			_jsii_.MemberProperty{JsiiProperty: "insecureTlsInput", GoGetter: "InsecureTlsInput"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "isPrimaryForScope", GoGetter: "IsPrimaryForScope"},
			_jsii_.MemberProperty{JsiiProperty: "isPrimaryForScopeInput", GoGetter: "IsPrimaryForScopeInput"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "maximumPageSize", GoGetter: "MaximumPageSize"},
			_jsii_.MemberProperty{JsiiProperty: "maximumPageSizeInput", GoGetter: "MaximumPageSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberMethod{JsiiMethod: "resetAccountAttributeMaps", GoMethod: "ResetAccountAttributeMaps"},
			_jsii_.MemberMethod{JsiiMethod: "resetAnonGroupSearch", GoMethod: "ResetAnonGroupSearch"},
			_jsii_.MemberMethod{JsiiMethod: "resetBindDn", GoMethod: "ResetBindDn"},
			_jsii_.MemberMethod{JsiiMethod: "resetBindPassword", GoMethod: "ResetBindPassword"},
			_jsii_.MemberMethod{JsiiMethod: "resetBindPasswordHmac", GoMethod: "ResetBindPasswordHmac"},
			_jsii_.MemberMethod{JsiiMethod: "resetCertificates", GoMethod: "ResetCertificates"},
			_jsii_.MemberMethod{JsiiMethod: "resetClientCertificate", GoMethod: "ResetClientCertificate"},
			_jsii_.MemberMethod{JsiiMethod: "resetClientCertificateKey", GoMethod: "ResetClientCertificateKey"},
			_jsii_.MemberMethod{JsiiMethod: "resetClientCertificateKeyHmac", GoMethod: "ResetClientCertificateKeyHmac"},
			_jsii_.MemberMethod{JsiiMethod: "resetDereferenceAliases", GoMethod: "ResetDereferenceAliases"},
			_jsii_.MemberMethod{JsiiMethod: "resetDescription", GoMethod: "ResetDescription"},
			_jsii_.MemberMethod{JsiiMethod: "resetDiscoverDn", GoMethod: "ResetDiscoverDn"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableGroups", GoMethod: "ResetEnableGroups"},
			_jsii_.MemberMethod{JsiiMethod: "resetGroupAttr", GoMethod: "ResetGroupAttr"},
			_jsii_.MemberMethod{JsiiMethod: "resetGroupDn", GoMethod: "ResetGroupDn"},
			_jsii_.MemberMethod{JsiiMethod: "resetGroupFilter", GoMethod: "ResetGroupFilter"},
			_jsii_.MemberMethod{JsiiMethod: "resetInsecureTls", GoMethod: "ResetInsecureTls"},
			_jsii_.MemberMethod{JsiiMethod: "resetIsPrimaryForScope", GoMethod: "ResetIsPrimaryForScope"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaximumPageSize", GoMethod: "ResetMaximumPageSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetName", GoMethod: "ResetName"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetStartTls", GoMethod: "ResetStartTls"},
			_jsii_.MemberMethod{JsiiMethod: "resetState", GoMethod: "ResetState"},
			_jsii_.MemberMethod{JsiiMethod: "resetType", GoMethod: "ResetType"},
			_jsii_.MemberMethod{JsiiMethod: "resetUpnDomain", GoMethod: "ResetUpnDomain"},
			_jsii_.MemberMethod{JsiiMethod: "resetUrls", GoMethod: "ResetUrls"},
			_jsii_.MemberMethod{JsiiMethod: "resetUserAttr", GoMethod: "ResetUserAttr"},
			_jsii_.MemberMethod{JsiiMethod: "resetUserDn", GoMethod: "ResetUserDn"},
			_jsii_.MemberMethod{JsiiMethod: "resetUserFilter", GoMethod: "ResetUserFilter"},
			_jsii_.MemberMethod{JsiiMethod: "resetUseTokenGroups", GoMethod: "ResetUseTokenGroups"},
			_jsii_.MemberProperty{JsiiProperty: "scopeId", GoGetter: "ScopeId"},
			_jsii_.MemberProperty{JsiiProperty: "scopeIdInput", GoGetter: "ScopeIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "startTls", GoGetter: "StartTls"},
			_jsii_.MemberProperty{JsiiProperty: "startTlsInput", GoGetter: "StartTlsInput"},
			_jsii_.MemberProperty{JsiiProperty: "state", GoGetter: "State"},
			_jsii_.MemberProperty{JsiiProperty: "stateInput", GoGetter: "StateInput"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "type", GoGetter: "Type"},
			_jsii_.MemberProperty{JsiiProperty: "typeInput", GoGetter: "TypeInput"},
			_jsii_.MemberProperty{JsiiProperty: "upnDomain", GoGetter: "UpnDomain"},
			_jsii_.MemberProperty{JsiiProperty: "upnDomainInput", GoGetter: "UpnDomainInput"},
			_jsii_.MemberProperty{JsiiProperty: "urls", GoGetter: "Urls"},
			_jsii_.MemberProperty{JsiiProperty: "urlsInput", GoGetter: "UrlsInput"},
			_jsii_.MemberProperty{JsiiProperty: "userAttr", GoGetter: "UserAttr"},
			_jsii_.MemberProperty{JsiiProperty: "userAttrInput", GoGetter: "UserAttrInput"},
			_jsii_.MemberProperty{JsiiProperty: "userDn", GoGetter: "UserDn"},
			_jsii_.MemberProperty{JsiiProperty: "userDnInput", GoGetter: "UserDnInput"},
			_jsii_.MemberProperty{JsiiProperty: "userFilter", GoGetter: "UserFilter"},
			_jsii_.MemberProperty{JsiiProperty: "userFilterInput", GoGetter: "UserFilterInput"},
			_jsii_.MemberProperty{JsiiProperty: "useTokenGroups", GoGetter: "UseTokenGroups"},
			_jsii_.MemberProperty{JsiiProperty: "useTokenGroupsInput", GoGetter: "UseTokenGroupsInput"},
		},
		func() interface{} {
			j := jsiiProxy_AuthMethodLdap{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-boundary.authMethodLdap.AuthMethodLdapConfig",
		reflect.TypeOf((*AuthMethodLdapConfig)(nil)).Elem(),
	)
}
